directories:
  output: dist-new-v5
  buildResources: build
appId: com.u3.draw
productName: U3 Draw
asar: false
files:
  - filter:
      - app/**/*
      - main.js
icon: null
win:
  target:
    - nsis
    - portable
electronVersion: 39.2.7
